
project_id = "poovixtfdbtmgkiehyea"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[functions]
[functions.send-sms]
verify_jwt = true

[functions.send-affirmation]
verify_jwt = true

[studio]
enabled = true
port = 54323
