// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://poovixtfdbtmgkiehyea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvb3ZpeHRmZGJ0bWdraWVoeWVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MDc3MDMsImV4cCI6MjA1Nzk4MzcwM30.rErrPOZSsIALc8-QGmijR73baUfxy8MKNym-v5HzbU0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);